/*
 * generated by Xtext
 */
package org.csail.genesis.ui;

import org.csail.genesis.ui.folding.GenesisFoldingRegionProvider;
import org.csail.genesis.ui.highlighting.GenesisHighlightingCalculator;
import org.csail.genesis.ui.highlighting.GenesisHighlightingConfiguration;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.folding.IFoldingRegionProvider;
import org.eclipse.xtext.ui.editor.syntaxcoloring.IHighlightingConfiguration;
import org.eclipse.xtext.ui.editor.syntaxcoloring.ISemanticHighlightingCalculator;

/**
 * Use this class to register components to be used within the IDE.
 */
public class GenesisUiModule extends org.csail.genesis.ui.AbstractGenesisUiModule {
	public GenesisUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	public Class<? extends IHighlightingConfiguration> bindIHighlightingConfiguration () {
	    return GenesisHighlightingConfiguration.class;
	}

	public Class<? extends ISemanticHighlightingCalculator> bindISemanticHighlightingCalculator(){
	    return GenesisHighlightingCalculator.class;
	}
	
	public Class<? extends IFoldingRegionProvider> bindIFoldingRegionProvider() {
        return GenesisFoldingRegionProvider.class;
    }
}
