/*
* generated by Xtext
*/
package org.csail.genesis.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.csail.genesis.services.GenesisGrammarAccess;

public class GenesisParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private GenesisGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.csail.genesis.parser.antlr.internal.InternalGenesisParser createParser(XtextTokenStream stream) {
		return new org.csail.genesis.parser.antlr.internal.InternalGenesisParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public GenesisGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(GenesisGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
