/*
* generated by Xtext
*/
package org.csail.genesis;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class GenesisUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.csail.genesis.ui.internal.GenesisActivator.getInstance().getInjector("org.csail.genesis.Genesis");
	}
	
}
