/*
* generated by Xtext
*/
package org.csail.genesis.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;


@Singleton
public class GenesisGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Model");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cHeaderAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cHeaderSentenceParserRuleCall_0_0 = (RuleCall)cHeaderAssignment_0.eContents().get(0);
		private final Assignment cSectionsAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cSectionsSectionParserRuleCall_1_0 = (RuleCall)cSectionsAssignment_1.eContents().get(0);
		
		//Model:
		//	header+=Sentence* sections+=Section*;
		public ParserRule getRule() { return rule; }

		//header+=Sentence* sections+=Section*
		public Group getGroup() { return cGroup; }

		//header+=Sentence*
		public Assignment getHeaderAssignment_0() { return cHeaderAssignment_0; }

		//Sentence
		public RuleCall getHeaderSentenceParserRuleCall_0_0() { return cHeaderSentenceParserRuleCall_0_0; }

		//sections+=Section*
		public Assignment getSectionsAssignment_1() { return cSectionsAssignment_1; }

		//Section
		public RuleCall getSectionsSectionParserRuleCall_1_0() { return cSectionsSectionParserRuleCall_1_0; }
	}

	public class SectionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Section");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cCommonsenseKnowledgeParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cReflexiveKnowledgeParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cPerspectiveParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//Section:
		//	CommonsenseKnowledge | ReflexiveKnowledge | Perspective;
		public ParserRule getRule() { return rule; }

		//CommonsenseKnowledge | ReflexiveKnowledge | Perspective
		public Alternatives getAlternatives() { return cAlternatives; }

		//CommonsenseKnowledge
		public RuleCall getCommonsenseKnowledgeParserRuleCall_0() { return cCommonsenseKnowledgeParserRuleCall_0; }

		//ReflexiveKnowledge
		public RuleCall getReflexiveKnowledgeParserRuleCall_1() { return cReflexiveKnowledgeParserRuleCall_1; }

		//Perspective
		public RuleCall getPerspectiveParserRuleCall_2() { return cPerspectiveParserRuleCall_2; }
	}

	public class CommonsenseKnowledgeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "CommonsenseKnowledge");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cCommonsenseKnowledgeAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameCommonsenseKnowledgeHeaderParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Assignment cBodyAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cBodyDescriptionParserRuleCall_2_0 = (RuleCall)cBodyAssignment_2.eContents().get(0);
		
		//CommonsenseKnowledge:
		//	{CommonsenseKnowledge} name=CommonsenseKnowledgeHeader body=Description;
		public ParserRule getRule() { return rule; }

		//{CommonsenseKnowledge} name=CommonsenseKnowledgeHeader body=Description
		public Group getGroup() { return cGroup; }

		//{CommonsenseKnowledge}
		public Action getCommonsenseKnowledgeAction_0() { return cCommonsenseKnowledgeAction_0; }

		//name=CommonsenseKnowledgeHeader
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//CommonsenseKnowledgeHeader
		public RuleCall getNameCommonsenseKnowledgeHeaderParserRuleCall_1_0() { return cNameCommonsenseKnowledgeHeaderParserRuleCall_1_0; }

		//body=Description
		public Assignment getBodyAssignment_2() { return cBodyAssignment_2; }

		//Description
		public RuleCall getBodyDescriptionParserRuleCall_2_0() { return cBodyDescriptionParserRuleCall_2_0; }
	}

	public class CommonsenseKnowledgeHeaderElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "CommonsenseKnowledgeHeader");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cStartKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cCommonsenseKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cKnowledgeKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cFullStopKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//CommonsenseKnowledgeHeader:
		//	"Start" "commonsense" "knowledge" ".";
		public ParserRule getRule() { return rule; }

		//"Start" "commonsense" "knowledge" "."
		public Group getGroup() { return cGroup; }

		//"Start"
		public Keyword getStartKeyword_0() { return cStartKeyword_0; }

		//"commonsense"
		public Keyword getCommonsenseKeyword_1() { return cCommonsenseKeyword_1; }

		//"knowledge"
		public Keyword getKnowledgeKeyword_2() { return cKnowledgeKeyword_2; }

		//"."
		public Keyword getFullStopKeyword_3() { return cFullStopKeyword_3; }
	}

	public class ReflexiveKnowledgeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ReflexiveKnowledge");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cReflexiveKnowledgeAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameReflexiveKnowledgeHeaderParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Assignment cSubsectionsAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cSubsectionsReflexiveDescriptionParserRuleCall_2_0 = (RuleCall)cSubsectionsAssignment_2.eContents().get(0);
		
		//ReflexiveKnowledge:
		//	{ReflexiveKnowledge} name=ReflexiveKnowledgeHeader subsections+=ReflexiveDescription*;
		public ParserRule getRule() { return rule; }

		//{ReflexiveKnowledge} name=ReflexiveKnowledgeHeader subsections+=ReflexiveDescription*
		public Group getGroup() { return cGroup; }

		//{ReflexiveKnowledge}
		public Action getReflexiveKnowledgeAction_0() { return cReflexiveKnowledgeAction_0; }

		//name=ReflexiveKnowledgeHeader
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ReflexiveKnowledgeHeader
		public RuleCall getNameReflexiveKnowledgeHeaderParserRuleCall_1_0() { return cNameReflexiveKnowledgeHeaderParserRuleCall_1_0; }

		//subsections+=ReflexiveDescription*
		public Assignment getSubsectionsAssignment_2() { return cSubsectionsAssignment_2; }

		//ReflexiveDescription
		public RuleCall getSubsectionsReflexiveDescriptionParserRuleCall_2_0() { return cSubsectionsReflexiveDescriptionParserRuleCall_2_0; }
	}

	public class ReflexiveKnowledgeHeaderElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ReflexiveKnowledgeHeader");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cStartKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cReflexiveKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cKnowledgeKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cFullStopKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//ReflexiveKnowledgeHeader:
		//	"Start" "reflexive" "knowledge" ".";
		public ParserRule getRule() { return rule; }

		//"Start" "reflexive" "knowledge" "."
		public Group getGroup() { return cGroup; }

		//"Start"
		public Keyword getStartKeyword_0() { return cStartKeyword_0; }

		//"reflexive"
		public Keyword getReflexiveKeyword_1() { return cReflexiveKeyword_1; }

		//"knowledge"
		public Keyword getKnowledgeKeyword_2() { return cKnowledgeKeyword_2; }

		//"."
		public Keyword getFullStopKeyword_3() { return cFullStopKeyword_3; }
	}

	public class ReflexiveDescriptionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ReflexiveDescription");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cReflexiveDescriptionAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameReflexiveDescriptionHeaderParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Assignment cBodyAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cBodyDescriptionParserRuleCall_2_0 = (RuleCall)cBodyAssignment_2.eContents().get(0);
		private final RuleCall cTheEndFooterParserRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		
		//ReflexiveDescription:
		//	{ReflexiveDescription} name=ReflexiveDescriptionHeader body=Description TheEndFooter;
		public ParserRule getRule() { return rule; }

		//{ReflexiveDescription} name=ReflexiveDescriptionHeader body=Description TheEndFooter
		public Group getGroup() { return cGroup; }

		//{ReflexiveDescription}
		public Action getReflexiveDescriptionAction_0() { return cReflexiveDescriptionAction_0; }

		//name=ReflexiveDescriptionHeader
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ReflexiveDescriptionHeader
		public RuleCall getNameReflexiveDescriptionHeaderParserRuleCall_1_0() { return cNameReflexiveDescriptionHeaderParserRuleCall_1_0; }

		//body=Description
		public Assignment getBodyAssignment_2() { return cBodyAssignment_2; }

		//Description
		public RuleCall getBodyDescriptionParserRuleCall_2_0() { return cBodyDescriptionParserRuleCall_2_0; }

		//TheEndFooter
		public RuleCall getTheEndFooterParserRuleCall_3() { return cTheEndFooterParserRuleCall_3; }
	}

	public class TheEndFooterElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "TheEndFooter");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTheKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cEndKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cFullStopKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//TheEndFooter:
		//	"The" "end" ".";
		public ParserRule getRule() { return rule; }

		//"The" "end" "."
		public Group getGroup() { return cGroup; }

		//"The"
		public Keyword getTheKeyword_0() { return cTheKeyword_0; }

		//"end"
		public Keyword getEndKeyword_1() { return cEndKeyword_1; }

		//"."
		public Keyword getFullStopKeyword_2() { return cFullStopKeyword_2; }
	}

	public class ReflexiveDescriptionHeaderElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ReflexiveDescriptionHeader");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cStartKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cDescriptionKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cOfKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final RuleCall cQUOTED_TEXTTerminalRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		private final Keyword cFullStopKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//ReflexiveDescriptionHeader:
		//	"Start" "description" "of" QUOTED_TEXT ".";
		public ParserRule getRule() { return rule; }

		//"Start" "description" "of" QUOTED_TEXT "."
		public Group getGroup() { return cGroup; }

		//"Start"
		public Keyword getStartKeyword_0() { return cStartKeyword_0; }

		//"description"
		public Keyword getDescriptionKeyword_1() { return cDescriptionKeyword_1; }

		//"of"
		public Keyword getOfKeyword_2() { return cOfKeyword_2; }

		//QUOTED_TEXT
		public RuleCall getQUOTED_TEXTTerminalRuleCall_3() { return cQUOTED_TEXTTerminalRuleCall_3; }

		//"."
		public Keyword getFullStopKeyword_4() { return cFullStopKeyword_4; }
	}

	public class PerspectiveElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Perspective");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cPerspectiveAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNamePerspectiveHeaderParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Assignment cSubsectionsAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cSubsectionsStoryParserRuleCall_2_0 = (RuleCall)cSubsectionsAssignment_2.eContents().get(0);
		
		//Perspective:
		//	{Perspective} name=PerspectiveHeader subsections+=Story*;
		public ParserRule getRule() { return rule; }

		//{Perspective} name=PerspectiveHeader subsections+=Story*
		public Group getGroup() { return cGroup; }

		//{Perspective}
		public Action getPerspectiveAction_0() { return cPerspectiveAction_0; }

		//name=PerspectiveHeader
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//PerspectiveHeader
		public RuleCall getNamePerspectiveHeaderParserRuleCall_1_0() { return cNamePerspectiveHeaderParserRuleCall_1_0; }

		//subsections+=Story*
		public Assignment getSubsectionsAssignment_2() { return cSubsectionsAssignment_2; }

		//Story
		public RuleCall getSubsectionsStoryParserRuleCall_2_0() { return cSubsectionsStoryParserRuleCall_2_0; }
	}

	public class PerspectiveHeaderElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "PerspectiveHeader");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cWORDTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Keyword cPerspectiveKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cFullStopKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//PerspectiveHeader:
		//	WORD "perspective" ".";
		public ParserRule getRule() { return rule; }

		//WORD "perspective" "."
		public Group getGroup() { return cGroup; }

		//WORD
		public RuleCall getWORDTerminalRuleCall_0() { return cWORDTerminalRuleCall_0; }

		//"perspective"
		public Keyword getPerspectiveKeyword_1() { return cPerspectiveKeyword_1; }

		//"."
		public Keyword getFullStopKeyword_2() { return cFullStopKeyword_2; }
	}

	public class StoryElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Story");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cStoryAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameStoryHeaderParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Assignment cBodyAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cBodyDescriptionParserRuleCall_2_0 = (RuleCall)cBodyAssignment_2.eContents().get(0);
		private final RuleCall cTheEndFooterParserRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		
		//Story:
		//	{Story} name=StoryHeader body=Description TheEndFooter;
		public ParserRule getRule() { return rule; }

		//{Story} name=StoryHeader body=Description TheEndFooter
		public Group getGroup() { return cGroup; }

		//{Story}
		public Action getStoryAction_0() { return cStoryAction_0; }

		//name=StoryHeader
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//StoryHeader
		public RuleCall getNameStoryHeaderParserRuleCall_1_0() { return cNameStoryHeaderParserRuleCall_1_0; }

		//body=Description
		public Assignment getBodyAssignment_2() { return cBodyAssignment_2; }

		//Description
		public RuleCall getBodyDescriptionParserRuleCall_2_0() { return cBodyDescriptionParserRuleCall_2_0; }

		//TheEndFooter
		public RuleCall getTheEndFooterParserRuleCall_3() { return cTheEndFooterParserRuleCall_3; }
	}

	public class StoryHeaderElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "StoryHeader");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cStartKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cStoryKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cTitledKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final RuleCall cQUOTED_TEXTTerminalRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		private final Keyword cFullStopKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//StoryHeader:
		//	"Start" "story" "titled" QUOTED_TEXT ".";
		public ParserRule getRule() { return rule; }

		//"Start" "story" "titled" QUOTED_TEXT "."
		public Group getGroup() { return cGroup; }

		//"Start"
		public Keyword getStartKeyword_0() { return cStartKeyword_0; }

		//"story"
		public Keyword getStoryKeyword_1() { return cStoryKeyword_1; }

		//"titled"
		public Keyword getTitledKeyword_2() { return cTitledKeyword_2; }

		//QUOTED_TEXT
		public RuleCall getQUOTED_TEXTTerminalRuleCall_3() { return cQUOTED_TEXTTerminalRuleCall_3; }

		//"."
		public Keyword getFullStopKeyword_4() { return cFullStopKeyword_4; }
	}

	public class DescriptionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Description");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cDescriptionAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cSentencesAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cSentencesSentenceParserRuleCall_1_0 = (RuleCall)cSentencesAssignment_1.eContents().get(0);
		
		////ArbitrarySentences:
		////    {ArbitrarySentences}
		////    (sentences += Sentence)*
		////;
		//Description:
		//	{Description} sentences+=Sentence*;
		public ParserRule getRule() { return rule; }

		//{Description} sentences+=Sentence*
		public Group getGroup() { return cGroup; }

		//{Description}
		public Action getDescriptionAction_0() { return cDescriptionAction_0; }

		//sentences+=Sentence*
		public Assignment getSentencesAssignment_1() { return cSentencesAssignment_1; }

		//Sentence
		public RuleCall getSentencesSentenceParserRuleCall_1_0() { return cSentencesSentenceParserRuleCall_1_0; }
	}

	public class SentenceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Sentence");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cSentenceAction_0 = (Action)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Alternatives cAlternatives_1_0 = (Alternatives)cGroup_1.eContents().get(0);
		private final Assignment cFragmentsAssignment_1_0_0 = (Assignment)cAlternatives_1_0.eContents().get(0);
		private final RuleCall cFragmentsREGULAR_FRAGMENTParserRuleCall_1_0_0_0 = (RuleCall)cFragmentsAssignment_1_0_0.eContents().get(0);
		private final Group cGroup_1_0_1 = (Group)cAlternatives_1_0.eContents().get(1);
		private final Assignment cFragmentsAssignment_1_0_1_0 = (Assignment)cGroup_1_0_1.eContents().get(0);
		private final Keyword cFragmentsStartKeyword_1_0_1_0_0 = (Keyword)cFragmentsAssignment_1_0_1_0.eContents().get(0);
		private final Assignment cFragmentsAssignment_1_0_1_1 = (Assignment)cGroup_1_0_1.eContents().get(1);
		private final Keyword cFragmentsKnowledgeKeyword_1_0_1_1_0 = (Keyword)cFragmentsAssignment_1_0_1_1.eContents().get(0);
		private final Group cGroup_1_0_2 = (Group)cAlternatives_1_0.eContents().get(2);
		private final Assignment cFragmentsAssignment_1_0_2_0 = (Assignment)cGroup_1_0_2.eContents().get(0);
		private final Keyword cFragmentsStartKeyword_1_0_2_0_0 = (Keyword)cFragmentsAssignment_1_0_2_0.eContents().get(0);
		private final Assignment cFragmentsAssignment_1_0_2_1 = (Assignment)cGroup_1_0_2.eContents().get(1);
		private final Keyword cFragmentsCommonsenseKeyword_1_0_2_1_0 = (Keyword)cFragmentsAssignment_1_0_2_1.eContents().get(0);
		private final Assignment cFragmentsAssignment_1_0_2_2 = (Assignment)cGroup_1_0_2.eContents().get(2);
		private final RuleCall cFragmentsREGULAR_FRAGMENTParserRuleCall_1_0_2_2_0 = (RuleCall)cFragmentsAssignment_1_0_2_2.eContents().get(0);
		private final Group cGroup_1_0_3 = (Group)cAlternatives_1_0.eContents().get(3);
		private final Assignment cFragmentsAssignment_1_0_3_0 = (Assignment)cGroup_1_0_3.eContents().get(0);
		private final Keyword cFragmentsStartKeyword_1_0_3_0_0 = (Keyword)cFragmentsAssignment_1_0_3_0.eContents().get(0);
		private final Assignment cFragmentsAssignment_1_0_3_1 = (Assignment)cGroup_1_0_3.eContents().get(1);
		private final Keyword cFragmentsTheKeyword_1_0_3_1_0 = (Keyword)cFragmentsAssignment_1_0_3_1.eContents().get(0);
		private final Group cGroup_1_0_4 = (Group)cAlternatives_1_0.eContents().get(4);
		private final Assignment cFragmentsAssignment_1_0_4_0 = (Assignment)cGroup_1_0_4.eContents().get(0);
		private final Keyword cFragmentsStartKeyword_1_0_4_0_0 = (Keyword)cFragmentsAssignment_1_0_4_0.eContents().get(0);
		private final Assignment cFragmentsAssignment_1_0_4_1 = (Assignment)cGroup_1_0_4.eContents().get(1);
		private final Keyword cFragmentsEndKeyword_1_0_4_1_0 = (Keyword)cFragmentsAssignment_1_0_4_1.eContents().get(0);
		private final Group cGroup_1_0_5 = (Group)cAlternatives_1_0.eContents().get(5);
		private final Assignment cFragmentsAssignment_1_0_5_0 = (Assignment)cGroup_1_0_5.eContents().get(0);
		private final Keyword cFragmentsStartKeyword_1_0_5_0_0 = (Keyword)cFragmentsAssignment_1_0_5_0.eContents().get(0);
		private final Assignment cFragmentsAssignment_1_0_5_1 = (Assignment)cGroup_1_0_5.eContents().get(1);
		private final Keyword cFragmentsOfKeyword_1_0_5_1_0 = (Keyword)cFragmentsAssignment_1_0_5_1.eContents().get(0);
		private final Group cGroup_1_0_6 = (Group)cAlternatives_1_0.eContents().get(6);
		private final Assignment cFragmentsAssignment_1_0_6_0 = (Assignment)cGroup_1_0_6.eContents().get(0);
		private final Keyword cFragmentsStartKeyword_1_0_6_0_0 = (Keyword)cFragmentsAssignment_1_0_6_0.eContents().get(0);
		private final Assignment cFragmentsAssignment_1_0_6_1 = (Assignment)cGroup_1_0_6.eContents().get(1);
		private final Keyword cFragmentsStartKeyword_1_0_6_1_0 = (Keyword)cFragmentsAssignment_1_0_6_1.eContents().get(0);
		private final Group cGroup_1_0_7 = (Group)cAlternatives_1_0.eContents().get(7);
		private final Assignment cFragmentsAssignment_1_0_7_0 = (Assignment)cGroup_1_0_7.eContents().get(0);
		private final Keyword cFragmentsStartKeyword_1_0_7_0_0 = (Keyword)cFragmentsAssignment_1_0_7_0.eContents().get(0);
		private final Assignment cFragmentsAssignment_1_0_7_1 = (Assignment)cGroup_1_0_7.eContents().get(1);
		private final RuleCall cFragmentsREGULAR_FRAGMENTParserRuleCall_1_0_7_1_0 = (RuleCall)cFragmentsAssignment_1_0_7_1.eContents().get(0);
		private final Assignment cFragmentsAssignment_1_0_8 = (Assignment)cAlternatives_1_0.eContents().get(8);
		private final Keyword cFragmentsKnowledgeKeyword_1_0_8_0 = (Keyword)cFragmentsAssignment_1_0_8.eContents().get(0);
		private final Assignment cFragmentsAssignment_1_0_9 = (Assignment)cAlternatives_1_0.eContents().get(9);
		private final Keyword cFragmentsCommonsenseKeyword_1_0_9_0 = (Keyword)cFragmentsAssignment_1_0_9.eContents().get(0);
		private final Group cGroup_1_0_10 = (Group)cAlternatives_1_0.eContents().get(10);
		private final Assignment cFragmentsAssignment_1_0_10_0 = (Assignment)cGroup_1_0_10.eContents().get(0);
		private final Keyword cFragmentsStartKeyword_1_0_10_0_0 = (Keyword)cFragmentsAssignment_1_0_10_0.eContents().get(0);
		private final Assignment cFragmentsAssignment_1_0_10_1 = (Assignment)cGroup_1_0_10.eContents().get(1);
		private final Keyword cFragmentsReflexiveKeyword_1_0_10_1_0 = (Keyword)cFragmentsAssignment_1_0_10_1.eContents().get(0);
		private final Assignment cFragmentsAssignment_1_0_10_2 = (Assignment)cGroup_1_0_10.eContents().get(2);
		private final RuleCall cFragmentsREGULAR_FRAGMENTParserRuleCall_1_0_10_2_0 = (RuleCall)cFragmentsAssignment_1_0_10_2.eContents().get(0);
		private final Assignment cFragmentsAssignment_1_0_11 = (Assignment)cAlternatives_1_0.eContents().get(11);
		private final Keyword cFragmentsReflexiveKeyword_1_0_11_0 = (Keyword)cFragmentsAssignment_1_0_11.eContents().get(0);
		private final Group cGroup_1_0_12 = (Group)cAlternatives_1_0.eContents().get(12);
		private final Assignment cFragmentsAssignment_1_0_12_0 = (Assignment)cGroup_1_0_12.eContents().get(0);
		private final Keyword cFragmentsStartKeyword_1_0_12_0_0 = (Keyword)cFragmentsAssignment_1_0_12_0.eContents().get(0);
		private final Assignment cFragmentsAssignment_1_0_12_1 = (Assignment)cGroup_1_0_12.eContents().get(1);
		private final Keyword cFragmentsDescriptionKeyword_1_0_12_1_0 = (Keyword)cFragmentsAssignment_1_0_12_1.eContents().get(0);
		private final Assignment cFragmentsAssignment_1_0_12_2 = (Assignment)cGroup_1_0_12.eContents().get(2);
		private final RuleCall cFragmentsREGULAR_FRAGMENTParserRuleCall_1_0_12_2_0 = (RuleCall)cFragmentsAssignment_1_0_12_2.eContents().get(0);
		private final Assignment cFragmentsAssignment_1_0_13 = (Assignment)cAlternatives_1_0.eContents().get(13);
		private final Keyword cFragmentsDescriptionKeyword_1_0_13_0 = (Keyword)cFragmentsAssignment_1_0_13.eContents().get(0);
		private final Assignment cFragmentsAssignment_1_0_14 = (Assignment)cAlternatives_1_0.eContents().get(14);
		private final Keyword cFragmentsOfKeyword_1_0_14_0 = (Keyword)cFragmentsAssignment_1_0_14.eContents().get(0);
		private final Group cGroup_1_0_15 = (Group)cAlternatives_1_0.eContents().get(15);
		private final Assignment cFragmentsAssignment_1_0_15_0 = (Assignment)cGroup_1_0_15.eContents().get(0);
		private final Keyword cFragmentsTheKeyword_1_0_15_0_0 = (Keyword)cFragmentsAssignment_1_0_15_0.eContents().get(0);
		private final Assignment cFragmentsAssignment_1_0_15_1 = (Assignment)cGroup_1_0_15.eContents().get(1);
		private final Keyword cFragmentsCommonsenseKeyword_1_0_15_1_0 = (Keyword)cFragmentsAssignment_1_0_15_1.eContents().get(0);
		private final Group cGroup_1_0_16 = (Group)cAlternatives_1_0.eContents().get(16);
		private final Assignment cFragmentsAssignment_1_0_16_0 = (Assignment)cGroup_1_0_16.eContents().get(0);
		private final Keyword cFragmentsTheKeyword_1_0_16_0_0 = (Keyword)cFragmentsAssignment_1_0_16_0.eContents().get(0);
		private final Assignment cFragmentsAssignment_1_0_16_1 = (Assignment)cGroup_1_0_16.eContents().get(1);
		private final Keyword cFragmentsKnowledgeKeyword_1_0_16_1_0 = (Keyword)cFragmentsAssignment_1_0_16_1.eContents().get(0);
		private final Group cGroup_1_0_17 = (Group)cAlternatives_1_0.eContents().get(17);
		private final Assignment cFragmentsAssignment_1_0_17_0 = (Assignment)cGroup_1_0_17.eContents().get(0);
		private final Keyword cFragmentsTheKeyword_1_0_17_0_0 = (Keyword)cFragmentsAssignment_1_0_17_0.eContents().get(0);
		private final Assignment cFragmentsAssignment_1_0_17_1 = (Assignment)cGroup_1_0_17.eContents().get(1);
		private final Keyword cFragmentsReflexiveKeyword_1_0_17_1_0 = (Keyword)cFragmentsAssignment_1_0_17_1.eContents().get(0);
		private final Group cGroup_1_0_18 = (Group)cAlternatives_1_0.eContents().get(18);
		private final Assignment cFragmentsAssignment_1_0_18_0 = (Assignment)cGroup_1_0_18.eContents().get(0);
		private final Keyword cFragmentsTheKeyword_1_0_18_0_0 = (Keyword)cFragmentsAssignment_1_0_18_0.eContents().get(0);
		private final Assignment cFragmentsAssignment_1_0_18_1 = (Assignment)cGroup_1_0_18.eContents().get(1);
		private final Keyword cFragmentsDescriptionKeyword_1_0_18_1_0 = (Keyword)cFragmentsAssignment_1_0_18_1.eContents().get(0);
		private final Group cGroup_1_0_19 = (Group)cAlternatives_1_0.eContents().get(19);
		private final Assignment cFragmentsAssignment_1_0_19_0 = (Assignment)cGroup_1_0_19.eContents().get(0);
		private final Keyword cFragmentsTheKeyword_1_0_19_0_0 = (Keyword)cFragmentsAssignment_1_0_19_0.eContents().get(0);
		private final Assignment cFragmentsAssignment_1_0_19_1 = (Assignment)cGroup_1_0_19.eContents().get(1);
		private final Keyword cFragmentsOfKeyword_1_0_19_1_0 = (Keyword)cFragmentsAssignment_1_0_19_1.eContents().get(0);
		private final Group cGroup_1_0_20 = (Group)cAlternatives_1_0.eContents().get(20);
		private final Assignment cFragmentsAssignment_1_0_20_0 = (Assignment)cGroup_1_0_20.eContents().get(0);
		private final Keyword cFragmentsTheKeyword_1_0_20_0_0 = (Keyword)cFragmentsAssignment_1_0_20_0.eContents().get(0);
		private final Assignment cFragmentsAssignment_1_0_20_1 = (Assignment)cGroup_1_0_20.eContents().get(1);
		private final Keyword cFragmentsStoryKeyword_1_0_20_1_0 = (Keyword)cFragmentsAssignment_1_0_20_1.eContents().get(0);
		private final Group cGroup_1_0_21 = (Group)cAlternatives_1_0.eContents().get(21);
		private final Assignment cFragmentsAssignment_1_0_21_0 = (Assignment)cGroup_1_0_21.eContents().get(0);
		private final Keyword cFragmentsTheKeyword_1_0_21_0_0 = (Keyword)cFragmentsAssignment_1_0_21_0.eContents().get(0);
		private final Assignment cFragmentsAssignment_1_0_21_1 = (Assignment)cGroup_1_0_21.eContents().get(1);
		private final Keyword cFragmentsTitledKeyword_1_0_21_1_0 = (Keyword)cFragmentsAssignment_1_0_21_1.eContents().get(0);
		private final Group cGroup_1_0_22 = (Group)cAlternatives_1_0.eContents().get(22);
		private final Assignment cFragmentsAssignment_1_0_22_0 = (Assignment)cGroup_1_0_22.eContents().get(0);
		private final Keyword cFragmentsTheKeyword_1_0_22_0_0 = (Keyword)cFragmentsAssignment_1_0_22_0.eContents().get(0);
		private final Assignment cFragmentsAssignment_1_0_22_1 = (Assignment)cGroup_1_0_22.eContents().get(1);
		private final Keyword cFragmentsStartKeyword_1_0_22_1_0 = (Keyword)cFragmentsAssignment_1_0_22_1.eContents().get(0);
		private final Group cGroup_1_0_23 = (Group)cAlternatives_1_0.eContents().get(23);
		private final Assignment cFragmentsAssignment_1_0_23_0 = (Assignment)cGroup_1_0_23.eContents().get(0);
		private final Keyword cFragmentsTheKeyword_1_0_23_0_0 = (Keyword)cFragmentsAssignment_1_0_23_0.eContents().get(0);
		private final Assignment cFragmentsAssignment_1_0_23_1 = (Assignment)cGroup_1_0_23.eContents().get(1);
		private final Keyword cFragmentsTheKeyword_1_0_23_1_0 = (Keyword)cFragmentsAssignment_1_0_23_1.eContents().get(0);
		private final Group cGroup_1_0_24 = (Group)cAlternatives_1_0.eContents().get(24);
		private final Assignment cFragmentsAssignment_1_0_24_0 = (Assignment)cGroup_1_0_24.eContents().get(0);
		private final Keyword cFragmentsTheKeyword_1_0_24_0_0 = (Keyword)cFragmentsAssignment_1_0_24_0.eContents().get(0);
		private final Assignment cFragmentsAssignment_1_0_24_1 = (Assignment)cGroup_1_0_24.eContents().get(1);
		private final RuleCall cFragmentsREGULAR_FRAGMENTParserRuleCall_1_0_24_1_0 = (RuleCall)cFragmentsAssignment_1_0_24_1.eContents().get(0);
		private final Assignment cFragmentsAssignment_1_0_25 = (Assignment)cAlternatives_1_0.eContents().get(25);
		private final Keyword cFragmentsEndKeyword_1_0_25_0 = (Keyword)cFragmentsAssignment_1_0_25.eContents().get(0);
		private final Group cGroup_1_0_26 = (Group)cAlternatives_1_0.eContents().get(26);
		private final Assignment cFragmentsAssignment_1_0_26_0 = (Assignment)cGroup_1_0_26.eContents().get(0);
		private final Keyword cFragmentsStartKeyword_1_0_26_0_0 = (Keyword)cFragmentsAssignment_1_0_26_0.eContents().get(0);
		private final Assignment cFragmentsAssignment_1_0_26_1 = (Assignment)cGroup_1_0_26.eContents().get(1);
		private final Keyword cFragmentsTitledKeyword_1_0_26_1_0 = (Keyword)cFragmentsAssignment_1_0_26_1.eContents().get(0);
		private final Group cGroup_1_0_27 = (Group)cAlternatives_1_0.eContents().get(27);
		private final Assignment cFragmentsAssignment_1_0_27_0 = (Assignment)cGroup_1_0_27.eContents().get(0);
		private final Keyword cFragmentsStartKeyword_1_0_27_0_0 = (Keyword)cFragmentsAssignment_1_0_27_0.eContents().get(0);
		private final Assignment cFragmentsAssignment_1_0_27_1 = (Assignment)cGroup_1_0_27.eContents().get(1);
		private final Keyword cFragmentsStoryKeyword_1_0_27_1_0 = (Keyword)cFragmentsAssignment_1_0_27_1.eContents().get(0);
		private final Assignment cFragmentsAssignment_1_0_27_2 = (Assignment)cGroup_1_0_27.eContents().get(2);
		private final RuleCall cFragmentsREGULAR_FRAGMENTParserRuleCall_1_0_27_2_0 = (RuleCall)cFragmentsAssignment_1_0_27_2.eContents().get(0);
		private final Assignment cFragmentsAssignment_1_0_28 = (Assignment)cAlternatives_1_0.eContents().get(28);
		private final Keyword cFragmentsStoryKeyword_1_0_28_0 = (Keyword)cFragmentsAssignment_1_0_28.eContents().get(0);
		private final Assignment cFragmentsAssignment_1_0_29 = (Assignment)cAlternatives_1_0.eContents().get(29);
		private final Keyword cFragmentsTitledKeyword_1_0_29_0 = (Keyword)cFragmentsAssignment_1_0_29.eContents().get(0);
		private final Alternatives cAlternatives_1_1 = (Alternatives)cGroup_1.eContents().get(1);
		private final Assignment cFragmentsAssignment_1_1_0 = (Assignment)cAlternatives_1_1.eContents().get(0);
		private final Keyword cFragmentsStartKeyword_1_1_0_0 = (Keyword)cFragmentsAssignment_1_1_0.eContents().get(0);
		private final Assignment cFragmentsAssignment_1_1_1 = (Assignment)cAlternatives_1_1.eContents().get(1);
		private final Keyword cFragmentsTheKeyword_1_1_1_0 = (Keyword)cFragmentsAssignment_1_1_1.eContents().get(0);
		private final Group cGroup_1_1_2 = (Group)cAlternatives_1_1.eContents().get(2);
		private final Assignment cFragmentsAssignment_1_1_2_0 = (Assignment)cGroup_1_1_2.eContents().get(0);
		private final Keyword cFragmentsStartKeyword_1_1_2_0_0 = (Keyword)cFragmentsAssignment_1_1_2_0.eContents().get(0);
		private final Assignment cFragmentsAssignment_1_1_2_1 = (Assignment)cGroup_1_1_2.eContents().get(1);
		private final Keyword cFragmentsCommonsenseKeyword_1_1_2_1_0 = (Keyword)cFragmentsAssignment_1_1_2_1.eContents().get(0);
		private final Group cGroup_1_1_3 = (Group)cAlternatives_1_1.eContents().get(3);
		private final Assignment cFragmentsAssignment_1_1_3_0 = (Assignment)cGroup_1_1_3.eContents().get(0);
		private final Keyword cFragmentsStartKeyword_1_1_3_0_0 = (Keyword)cFragmentsAssignment_1_1_3_0.eContents().get(0);
		private final Assignment cFragmentsAssignment_1_1_3_1 = (Assignment)cGroup_1_1_3.eContents().get(1);
		private final Keyword cFragmentsReflexiveKeyword_1_1_3_1_0 = (Keyword)cFragmentsAssignment_1_1_3_1.eContents().get(0);
		private final Group cGroup_1_1_4 = (Group)cAlternatives_1_1.eContents().get(4);
		private final Assignment cFragmentsAssignment_1_1_4_0 = (Assignment)cGroup_1_1_4.eContents().get(0);
		private final Keyword cFragmentsStartKeyword_1_1_4_0_0 = (Keyword)cFragmentsAssignment_1_1_4_0.eContents().get(0);
		private final Assignment cFragmentsAssignment_1_1_4_1 = (Assignment)cGroup_1_1_4.eContents().get(1);
		private final Keyword cFragmentsDescriptionKeyword_1_1_4_1_0 = (Keyword)cFragmentsAssignment_1_1_4_1.eContents().get(0);
		private final Group cGroup_1_1_5 = (Group)cAlternatives_1_1.eContents().get(5);
		private final Assignment cFragmentsAssignment_1_1_5_0 = (Assignment)cGroup_1_1_5.eContents().get(0);
		private final Keyword cFragmentsStartKeyword_1_1_5_0_0 = (Keyword)cFragmentsAssignment_1_1_5_0.eContents().get(0);
		private final Assignment cFragmentsAssignment_1_1_5_1 = (Assignment)cGroup_1_1_5.eContents().get(1);
		private final Keyword cFragmentsStoryKeyword_1_1_5_1_0 = (Keyword)cFragmentsAssignment_1_1_5_1.eContents().get(0);
		private final Keyword cFullStopKeyword_1_2 = (Keyword)cGroup_1.eContents().get(2);
		
		//Sentence:
		//	{Sentence} ((fragments+=REGULAR_FRAGMENT //
		//	// "Start commonsense knowledge" handling.
		//	//
		//	//
		//	// "Start reflexive knowledge" handling.
		//	//
		//	//
		//	// "Start description of <title>" handling.
		//	//
		//	//
		//	// "The end" handling.
		//	//
		//	//
		//	// "Start story titled" handling.
		//	//
		//	//                //
		//	//                // "????? perspective" handling.
		//	//                //
		//	//                (fragments += "perspective")
		//	| fragments+="Start" fragments+="knowledge" | fragments+="Start" fragments+="commonsense" fragments+=REGULAR_FRAGMENT |
		//	fragments+="Start" fragments+="The" | fragments+="Start" fragments+="end" | fragments+="Start" fragments+="of" |
		//	fragments+="Start" fragments+="Start" | fragments+="Start" fragments+=REGULAR_FRAGMENT | fragments+="knowledge" |
		//	fragments+="commonsense" | fragments+="Start" fragments+="reflexive" fragments+=REGULAR_FRAGMENT |
		//	fragments+="reflexive" | fragments+="Start" fragments+="description" fragments+=REGULAR_FRAGMENT |
		//	fragments+="description" | fragments+="of" | fragments+="The" fragments+="commonsense" | fragments+="The"
		//	fragments+="knowledge" | fragments+="The" fragments+="reflexive" | fragments+="The" fragments+="description" |
		//	fragments+="The" fragments+="of" | fragments+="The" fragments+="story" | fragments+="The" fragments+="titled" |
		//	fragments+="The" fragments+="Start" | fragments+="The" fragments+="The" | fragments+="The" fragments+=REGULAR_FRAGMENT
		//	| fragments+="end" | fragments+="Start" fragments+="titled" | fragments+="Start" fragments+="story"
		//	fragments+=REGULAR_FRAGMENT | fragments+="story" | fragments+="titled")* (fragments+="Start" | fragments+="The" |
		//	fragments+="Start" fragments+="commonsense" | fragments+="Start" fragments+="reflexive" | fragments+="Start"
		//	fragments+="description" | fragments+="Start" fragments+="story")? ".");
		public ParserRule getRule() { return rule; }

		//{Sentence} ((fragments+=REGULAR_FRAGMENT //
		//// "Start commonsense knowledge" handling.
		////
		////
		//// "Start reflexive knowledge" handling.
		////
		////
		//// "Start description of <title>" handling.
		////
		////
		//// "The end" handling.
		////
		////
		//// "Start story titled" handling.
		////
		////                //
		////                // "????? perspective" handling.
		////                //
		////                (fragments += "perspective")
		//| fragments+="Start" fragments+="knowledge" | fragments+="Start" fragments+="commonsense" fragments+=REGULAR_FRAGMENT |
		//fragments+="Start" fragments+="The" | fragments+="Start" fragments+="end" | fragments+="Start" fragments+="of" |
		//fragments+="Start" fragments+="Start" | fragments+="Start" fragments+=REGULAR_FRAGMENT | fragments+="knowledge" |
		//fragments+="commonsense" | fragments+="Start" fragments+="reflexive" fragments+=REGULAR_FRAGMENT |
		//fragments+="reflexive" | fragments+="Start" fragments+="description" fragments+=REGULAR_FRAGMENT |
		//fragments+="description" | fragments+="of" | fragments+="The" fragments+="commonsense" | fragments+="The"
		//fragments+="knowledge" | fragments+="The" fragments+="reflexive" | fragments+="The" fragments+="description" |
		//fragments+="The" fragments+="of" | fragments+="The" fragments+="story" | fragments+="The" fragments+="titled" |
		//fragments+="The" fragments+="Start" | fragments+="The" fragments+="The" | fragments+="The" fragments+=REGULAR_FRAGMENT
		//| fragments+="end" | fragments+="Start" fragments+="titled" | fragments+="Start" fragments+="story"
		//fragments+=REGULAR_FRAGMENT | fragments+="story" | fragments+="titled")* (fragments+="Start" | fragments+="The" |
		//fragments+="Start" fragments+="commonsense" | fragments+="Start" fragments+="reflexive" | fragments+="Start"
		//fragments+="description" | fragments+="Start" fragments+="story")? ".")
		public Group getGroup() { return cGroup; }

		//{Sentence}
		public Action getSentenceAction_0() { return cSentenceAction_0; }

		//(fragments+=REGULAR_FRAGMENT //
		//// "Start commonsense knowledge" handling.
		////
		////
		//// "Start reflexive knowledge" handling.
		////
		////
		//// "Start description of <title>" handling.
		////
		////
		//// "The end" handling.
		////
		////
		//// "Start story titled" handling.
		////
		////                //
		////                // "????? perspective" handling.
		////                //
		////                (fragments += "perspective")
		//| fragments+="Start" fragments+="knowledge" | fragments+="Start" fragments+="commonsense" fragments+=REGULAR_FRAGMENT |
		//fragments+="Start" fragments+="The" | fragments+="Start" fragments+="end" | fragments+="Start" fragments+="of" |
		//fragments+="Start" fragments+="Start" | fragments+="Start" fragments+=REGULAR_FRAGMENT | fragments+="knowledge" |
		//fragments+="commonsense" | fragments+="Start" fragments+="reflexive" fragments+=REGULAR_FRAGMENT |
		//fragments+="reflexive" | fragments+="Start" fragments+="description" fragments+=REGULAR_FRAGMENT |
		//fragments+="description" | fragments+="of" | fragments+="The" fragments+="commonsense" | fragments+="The"
		//fragments+="knowledge" | fragments+="The" fragments+="reflexive" | fragments+="The" fragments+="description" |
		//fragments+="The" fragments+="of" | fragments+="The" fragments+="story" | fragments+="The" fragments+="titled" |
		//fragments+="The" fragments+="Start" | fragments+="The" fragments+="The" | fragments+="The" fragments+=REGULAR_FRAGMENT
		//| fragments+="end" | fragments+="Start" fragments+="titled" | fragments+="Start" fragments+="story"
		//fragments+=REGULAR_FRAGMENT | fragments+="story" | fragments+="titled")* (fragments+="Start" | fragments+="The" |
		//fragments+="Start" fragments+="commonsense" | fragments+="Start" fragments+="reflexive" | fragments+="Start"
		//fragments+="description" | fragments+="Start" fragments+="story")? "."
		public Group getGroup_1() { return cGroup_1; }

		//(fragments+=REGULAR_FRAGMENT //
		//// "Start commonsense knowledge" handling.
		////
		////
		//// "Start reflexive knowledge" handling.
		////
		////
		//// "Start description of <title>" handling.
		////
		////
		//// "The end" handling.
		////
		////
		//// "Start story titled" handling.
		////
		////                //
		////                // "????? perspective" handling.
		////                //
		////                (fragments += "perspective")
		//| fragments+="Start" fragments+="knowledge" | fragments+="Start" fragments+="commonsense" fragments+=REGULAR_FRAGMENT |
		//fragments+="Start" fragments+="The" | fragments+="Start" fragments+="end" | fragments+="Start" fragments+="of" |
		//fragments+="Start" fragments+="Start" | fragments+="Start" fragments+=REGULAR_FRAGMENT | fragments+="knowledge" |
		//fragments+="commonsense" | fragments+="Start" fragments+="reflexive" fragments+=REGULAR_FRAGMENT |
		//fragments+="reflexive" | fragments+="Start" fragments+="description" fragments+=REGULAR_FRAGMENT |
		//fragments+="description" | fragments+="of" | fragments+="The" fragments+="commonsense" | fragments+="The"
		//fragments+="knowledge" | fragments+="The" fragments+="reflexive" | fragments+="The" fragments+="description" |
		//fragments+="The" fragments+="of" | fragments+="The" fragments+="story" | fragments+="The" fragments+="titled" |
		//fragments+="The" fragments+="Start" | fragments+="The" fragments+="The" | fragments+="The" fragments+=REGULAR_FRAGMENT
		//| fragments+="end" | fragments+="Start" fragments+="titled" | fragments+="Start" fragments+="story"
		//fragments+=REGULAR_FRAGMENT | fragments+="story" | fragments+="titled")*
		public Alternatives getAlternatives_1_0() { return cAlternatives_1_0; }

		//fragments+=REGULAR_FRAGMENT
		public Assignment getFragmentsAssignment_1_0_0() { return cFragmentsAssignment_1_0_0; }

		//REGULAR_FRAGMENT
		public RuleCall getFragmentsREGULAR_FRAGMENTParserRuleCall_1_0_0_0() { return cFragmentsREGULAR_FRAGMENTParserRuleCall_1_0_0_0; }

		//fragments+="Start" fragments+="knowledge"
		public Group getGroup_1_0_1() { return cGroup_1_0_1; }

		//fragments+="Start"
		public Assignment getFragmentsAssignment_1_0_1_0() { return cFragmentsAssignment_1_0_1_0; }

		//"Start"
		public Keyword getFragmentsStartKeyword_1_0_1_0_0() { return cFragmentsStartKeyword_1_0_1_0_0; }

		//fragments+="knowledge"
		public Assignment getFragmentsAssignment_1_0_1_1() { return cFragmentsAssignment_1_0_1_1; }

		//"knowledge"
		public Keyword getFragmentsKnowledgeKeyword_1_0_1_1_0() { return cFragmentsKnowledgeKeyword_1_0_1_1_0; }

		//fragments+="Start" fragments+="commonsense" fragments+=REGULAR_FRAGMENT
		public Group getGroup_1_0_2() { return cGroup_1_0_2; }

		//fragments+="Start"
		public Assignment getFragmentsAssignment_1_0_2_0() { return cFragmentsAssignment_1_0_2_0; }

		//"Start"
		public Keyword getFragmentsStartKeyword_1_0_2_0_0() { return cFragmentsStartKeyword_1_0_2_0_0; }

		//fragments+="commonsense"
		public Assignment getFragmentsAssignment_1_0_2_1() { return cFragmentsAssignment_1_0_2_1; }

		//"commonsense"
		public Keyword getFragmentsCommonsenseKeyword_1_0_2_1_0() { return cFragmentsCommonsenseKeyword_1_0_2_1_0; }

		//fragments+=REGULAR_FRAGMENT
		public Assignment getFragmentsAssignment_1_0_2_2() { return cFragmentsAssignment_1_0_2_2; }

		//REGULAR_FRAGMENT
		public RuleCall getFragmentsREGULAR_FRAGMENTParserRuleCall_1_0_2_2_0() { return cFragmentsREGULAR_FRAGMENTParserRuleCall_1_0_2_2_0; }

		//fragments+="Start" fragments+="The"
		public Group getGroup_1_0_3() { return cGroup_1_0_3; }

		//fragments+="Start"
		public Assignment getFragmentsAssignment_1_0_3_0() { return cFragmentsAssignment_1_0_3_0; }

		//"Start"
		public Keyword getFragmentsStartKeyword_1_0_3_0_0() { return cFragmentsStartKeyword_1_0_3_0_0; }

		//fragments+="The"
		public Assignment getFragmentsAssignment_1_0_3_1() { return cFragmentsAssignment_1_0_3_1; }

		//"The"
		public Keyword getFragmentsTheKeyword_1_0_3_1_0() { return cFragmentsTheKeyword_1_0_3_1_0; }

		//fragments+="Start" fragments+="end"
		public Group getGroup_1_0_4() { return cGroup_1_0_4; }

		//fragments+="Start"
		public Assignment getFragmentsAssignment_1_0_4_0() { return cFragmentsAssignment_1_0_4_0; }

		//"Start"
		public Keyword getFragmentsStartKeyword_1_0_4_0_0() { return cFragmentsStartKeyword_1_0_4_0_0; }

		//fragments+="end"
		public Assignment getFragmentsAssignment_1_0_4_1() { return cFragmentsAssignment_1_0_4_1; }

		//"end"
		public Keyword getFragmentsEndKeyword_1_0_4_1_0() { return cFragmentsEndKeyword_1_0_4_1_0; }

		//fragments+="Start" fragments+="of"
		public Group getGroup_1_0_5() { return cGroup_1_0_5; }

		//fragments+="Start"
		public Assignment getFragmentsAssignment_1_0_5_0() { return cFragmentsAssignment_1_0_5_0; }

		//"Start"
		public Keyword getFragmentsStartKeyword_1_0_5_0_0() { return cFragmentsStartKeyword_1_0_5_0_0; }

		//fragments+="of"
		public Assignment getFragmentsAssignment_1_0_5_1() { return cFragmentsAssignment_1_0_5_1; }

		//"of"
		public Keyword getFragmentsOfKeyword_1_0_5_1_0() { return cFragmentsOfKeyword_1_0_5_1_0; }

		//fragments+="Start" fragments+="Start"
		public Group getGroup_1_0_6() { return cGroup_1_0_6; }

		//fragments+="Start"
		public Assignment getFragmentsAssignment_1_0_6_0() { return cFragmentsAssignment_1_0_6_0; }

		//"Start"
		public Keyword getFragmentsStartKeyword_1_0_6_0_0() { return cFragmentsStartKeyword_1_0_6_0_0; }

		//fragments+="Start"
		public Assignment getFragmentsAssignment_1_0_6_1() { return cFragmentsAssignment_1_0_6_1; }

		//"Start"
		public Keyword getFragmentsStartKeyword_1_0_6_1_0() { return cFragmentsStartKeyword_1_0_6_1_0; }

		//fragments+="Start" fragments+=REGULAR_FRAGMENT
		public Group getGroup_1_0_7() { return cGroup_1_0_7; }

		//fragments+="Start"
		public Assignment getFragmentsAssignment_1_0_7_0() { return cFragmentsAssignment_1_0_7_0; }

		//"Start"
		public Keyword getFragmentsStartKeyword_1_0_7_0_0() { return cFragmentsStartKeyword_1_0_7_0_0; }

		//fragments+=REGULAR_FRAGMENT
		public Assignment getFragmentsAssignment_1_0_7_1() { return cFragmentsAssignment_1_0_7_1; }

		//REGULAR_FRAGMENT
		public RuleCall getFragmentsREGULAR_FRAGMENTParserRuleCall_1_0_7_1_0() { return cFragmentsREGULAR_FRAGMENTParserRuleCall_1_0_7_1_0; }

		//fragments+="knowledge"
		public Assignment getFragmentsAssignment_1_0_8() { return cFragmentsAssignment_1_0_8; }

		//"knowledge"
		public Keyword getFragmentsKnowledgeKeyword_1_0_8_0() { return cFragmentsKnowledgeKeyword_1_0_8_0; }

		//fragments+="commonsense"
		public Assignment getFragmentsAssignment_1_0_9() { return cFragmentsAssignment_1_0_9; }

		//"commonsense"
		public Keyword getFragmentsCommonsenseKeyword_1_0_9_0() { return cFragmentsCommonsenseKeyword_1_0_9_0; }

		//fragments+="Start" fragments+="reflexive" fragments+=REGULAR_FRAGMENT
		public Group getGroup_1_0_10() { return cGroup_1_0_10; }

		//fragments+="Start"
		public Assignment getFragmentsAssignment_1_0_10_0() { return cFragmentsAssignment_1_0_10_0; }

		//"Start"
		public Keyword getFragmentsStartKeyword_1_0_10_0_0() { return cFragmentsStartKeyword_1_0_10_0_0; }

		//fragments+="reflexive"
		public Assignment getFragmentsAssignment_1_0_10_1() { return cFragmentsAssignment_1_0_10_1; }

		//"reflexive"
		public Keyword getFragmentsReflexiveKeyword_1_0_10_1_0() { return cFragmentsReflexiveKeyword_1_0_10_1_0; }

		//fragments+=REGULAR_FRAGMENT
		public Assignment getFragmentsAssignment_1_0_10_2() { return cFragmentsAssignment_1_0_10_2; }

		//REGULAR_FRAGMENT
		public RuleCall getFragmentsREGULAR_FRAGMENTParserRuleCall_1_0_10_2_0() { return cFragmentsREGULAR_FRAGMENTParserRuleCall_1_0_10_2_0; }

		//fragments+="reflexive"
		public Assignment getFragmentsAssignment_1_0_11() { return cFragmentsAssignment_1_0_11; }

		//"reflexive"
		public Keyword getFragmentsReflexiveKeyword_1_0_11_0() { return cFragmentsReflexiveKeyword_1_0_11_0; }

		//fragments+="Start" fragments+="description" fragments+=REGULAR_FRAGMENT
		public Group getGroup_1_0_12() { return cGroup_1_0_12; }

		//fragments+="Start"
		public Assignment getFragmentsAssignment_1_0_12_0() { return cFragmentsAssignment_1_0_12_0; }

		//"Start"
		public Keyword getFragmentsStartKeyword_1_0_12_0_0() { return cFragmentsStartKeyword_1_0_12_0_0; }

		//fragments+="description"
		public Assignment getFragmentsAssignment_1_0_12_1() { return cFragmentsAssignment_1_0_12_1; }

		//"description"
		public Keyword getFragmentsDescriptionKeyword_1_0_12_1_0() { return cFragmentsDescriptionKeyword_1_0_12_1_0; }

		//fragments+=REGULAR_FRAGMENT
		public Assignment getFragmentsAssignment_1_0_12_2() { return cFragmentsAssignment_1_0_12_2; }

		//REGULAR_FRAGMENT
		public RuleCall getFragmentsREGULAR_FRAGMENTParserRuleCall_1_0_12_2_0() { return cFragmentsREGULAR_FRAGMENTParserRuleCall_1_0_12_2_0; }

		//fragments+="description"
		public Assignment getFragmentsAssignment_1_0_13() { return cFragmentsAssignment_1_0_13; }

		//"description"
		public Keyword getFragmentsDescriptionKeyword_1_0_13_0() { return cFragmentsDescriptionKeyword_1_0_13_0; }

		//fragments+="of"
		public Assignment getFragmentsAssignment_1_0_14() { return cFragmentsAssignment_1_0_14; }

		//"of"
		public Keyword getFragmentsOfKeyword_1_0_14_0() { return cFragmentsOfKeyword_1_0_14_0; }

		//fragments+="The" fragments+="commonsense"
		public Group getGroup_1_0_15() { return cGroup_1_0_15; }

		//fragments+="The"
		public Assignment getFragmentsAssignment_1_0_15_0() { return cFragmentsAssignment_1_0_15_0; }

		//"The"
		public Keyword getFragmentsTheKeyword_1_0_15_0_0() { return cFragmentsTheKeyword_1_0_15_0_0; }

		//fragments+="commonsense"
		public Assignment getFragmentsAssignment_1_0_15_1() { return cFragmentsAssignment_1_0_15_1; }

		//"commonsense"
		public Keyword getFragmentsCommonsenseKeyword_1_0_15_1_0() { return cFragmentsCommonsenseKeyword_1_0_15_1_0; }

		//fragments+="The" fragments+="knowledge"
		public Group getGroup_1_0_16() { return cGroup_1_0_16; }

		//fragments+="The"
		public Assignment getFragmentsAssignment_1_0_16_0() { return cFragmentsAssignment_1_0_16_0; }

		//"The"
		public Keyword getFragmentsTheKeyword_1_0_16_0_0() { return cFragmentsTheKeyword_1_0_16_0_0; }

		//fragments+="knowledge"
		public Assignment getFragmentsAssignment_1_0_16_1() { return cFragmentsAssignment_1_0_16_1; }

		//"knowledge"
		public Keyword getFragmentsKnowledgeKeyword_1_0_16_1_0() { return cFragmentsKnowledgeKeyword_1_0_16_1_0; }

		//fragments+="The" fragments+="reflexive"
		public Group getGroup_1_0_17() { return cGroup_1_0_17; }

		//fragments+="The"
		public Assignment getFragmentsAssignment_1_0_17_0() { return cFragmentsAssignment_1_0_17_0; }

		//"The"
		public Keyword getFragmentsTheKeyword_1_0_17_0_0() { return cFragmentsTheKeyword_1_0_17_0_0; }

		//fragments+="reflexive"
		public Assignment getFragmentsAssignment_1_0_17_1() { return cFragmentsAssignment_1_0_17_1; }

		//"reflexive"
		public Keyword getFragmentsReflexiveKeyword_1_0_17_1_0() { return cFragmentsReflexiveKeyword_1_0_17_1_0; }

		//fragments+="The" fragments+="description"
		public Group getGroup_1_0_18() { return cGroup_1_0_18; }

		//fragments+="The"
		public Assignment getFragmentsAssignment_1_0_18_0() { return cFragmentsAssignment_1_0_18_0; }

		//"The"
		public Keyword getFragmentsTheKeyword_1_0_18_0_0() { return cFragmentsTheKeyword_1_0_18_0_0; }

		//fragments+="description"
		public Assignment getFragmentsAssignment_1_0_18_1() { return cFragmentsAssignment_1_0_18_1; }

		//"description"
		public Keyword getFragmentsDescriptionKeyword_1_0_18_1_0() { return cFragmentsDescriptionKeyword_1_0_18_1_0; }

		//fragments+="The" fragments+="of"
		public Group getGroup_1_0_19() { return cGroup_1_0_19; }

		//fragments+="The"
		public Assignment getFragmentsAssignment_1_0_19_0() { return cFragmentsAssignment_1_0_19_0; }

		//"The"
		public Keyword getFragmentsTheKeyword_1_0_19_0_0() { return cFragmentsTheKeyword_1_0_19_0_0; }

		//fragments+="of"
		public Assignment getFragmentsAssignment_1_0_19_1() { return cFragmentsAssignment_1_0_19_1; }

		//"of"
		public Keyword getFragmentsOfKeyword_1_0_19_1_0() { return cFragmentsOfKeyword_1_0_19_1_0; }

		//fragments+="The" fragments+="story"
		public Group getGroup_1_0_20() { return cGroup_1_0_20; }

		//fragments+="The"
		public Assignment getFragmentsAssignment_1_0_20_0() { return cFragmentsAssignment_1_0_20_0; }

		//"The"
		public Keyword getFragmentsTheKeyword_1_0_20_0_0() { return cFragmentsTheKeyword_1_0_20_0_0; }

		//fragments+="story"
		public Assignment getFragmentsAssignment_1_0_20_1() { return cFragmentsAssignment_1_0_20_1; }

		//"story"
		public Keyword getFragmentsStoryKeyword_1_0_20_1_0() { return cFragmentsStoryKeyword_1_0_20_1_0; }

		//fragments+="The" fragments+="titled"
		public Group getGroup_1_0_21() { return cGroup_1_0_21; }

		//fragments+="The"
		public Assignment getFragmentsAssignment_1_0_21_0() { return cFragmentsAssignment_1_0_21_0; }

		//"The"
		public Keyword getFragmentsTheKeyword_1_0_21_0_0() { return cFragmentsTheKeyword_1_0_21_0_0; }

		//fragments+="titled"
		public Assignment getFragmentsAssignment_1_0_21_1() { return cFragmentsAssignment_1_0_21_1; }

		//"titled"
		public Keyword getFragmentsTitledKeyword_1_0_21_1_0() { return cFragmentsTitledKeyword_1_0_21_1_0; }

		//fragments+="The" fragments+="Start"
		public Group getGroup_1_0_22() { return cGroup_1_0_22; }

		//fragments+="The"
		public Assignment getFragmentsAssignment_1_0_22_0() { return cFragmentsAssignment_1_0_22_0; }

		//"The"
		public Keyword getFragmentsTheKeyword_1_0_22_0_0() { return cFragmentsTheKeyword_1_0_22_0_0; }

		//fragments+="Start"
		public Assignment getFragmentsAssignment_1_0_22_1() { return cFragmentsAssignment_1_0_22_1; }

		//"Start"
		public Keyword getFragmentsStartKeyword_1_0_22_1_0() { return cFragmentsStartKeyword_1_0_22_1_0; }

		//fragments+="The" fragments+="The"
		public Group getGroup_1_0_23() { return cGroup_1_0_23; }

		//fragments+="The"
		public Assignment getFragmentsAssignment_1_0_23_0() { return cFragmentsAssignment_1_0_23_0; }

		//"The"
		public Keyword getFragmentsTheKeyword_1_0_23_0_0() { return cFragmentsTheKeyword_1_0_23_0_0; }

		//fragments+="The"
		public Assignment getFragmentsAssignment_1_0_23_1() { return cFragmentsAssignment_1_0_23_1; }

		//"The"
		public Keyword getFragmentsTheKeyword_1_0_23_1_0() { return cFragmentsTheKeyword_1_0_23_1_0; }

		//fragments+="The" fragments+=REGULAR_FRAGMENT
		public Group getGroup_1_0_24() { return cGroup_1_0_24; }

		//fragments+="The"
		public Assignment getFragmentsAssignment_1_0_24_0() { return cFragmentsAssignment_1_0_24_0; }

		//"The"
		public Keyword getFragmentsTheKeyword_1_0_24_0_0() { return cFragmentsTheKeyword_1_0_24_0_0; }

		//fragments+=REGULAR_FRAGMENT
		public Assignment getFragmentsAssignment_1_0_24_1() { return cFragmentsAssignment_1_0_24_1; }

		//REGULAR_FRAGMENT
		public RuleCall getFragmentsREGULAR_FRAGMENTParserRuleCall_1_0_24_1_0() { return cFragmentsREGULAR_FRAGMENTParserRuleCall_1_0_24_1_0; }

		//fragments+="end"
		public Assignment getFragmentsAssignment_1_0_25() { return cFragmentsAssignment_1_0_25; }

		//"end"
		public Keyword getFragmentsEndKeyword_1_0_25_0() { return cFragmentsEndKeyword_1_0_25_0; }

		//fragments+="Start" fragments+="titled"
		public Group getGroup_1_0_26() { return cGroup_1_0_26; }

		//fragments+="Start"
		public Assignment getFragmentsAssignment_1_0_26_0() { return cFragmentsAssignment_1_0_26_0; }

		//"Start"
		public Keyword getFragmentsStartKeyword_1_0_26_0_0() { return cFragmentsStartKeyword_1_0_26_0_0; }

		//fragments+="titled"
		public Assignment getFragmentsAssignment_1_0_26_1() { return cFragmentsAssignment_1_0_26_1; }

		//"titled"
		public Keyword getFragmentsTitledKeyword_1_0_26_1_0() { return cFragmentsTitledKeyword_1_0_26_1_0; }

		//fragments+="Start" fragments+="story" fragments+=REGULAR_FRAGMENT
		public Group getGroup_1_0_27() { return cGroup_1_0_27; }

		//fragments+="Start"
		public Assignment getFragmentsAssignment_1_0_27_0() { return cFragmentsAssignment_1_0_27_0; }

		//"Start"
		public Keyword getFragmentsStartKeyword_1_0_27_0_0() { return cFragmentsStartKeyword_1_0_27_0_0; }

		//fragments+="story"
		public Assignment getFragmentsAssignment_1_0_27_1() { return cFragmentsAssignment_1_0_27_1; }

		//"story"
		public Keyword getFragmentsStoryKeyword_1_0_27_1_0() { return cFragmentsStoryKeyword_1_0_27_1_0; }

		//fragments+=REGULAR_FRAGMENT
		public Assignment getFragmentsAssignment_1_0_27_2() { return cFragmentsAssignment_1_0_27_2; }

		//REGULAR_FRAGMENT
		public RuleCall getFragmentsREGULAR_FRAGMENTParserRuleCall_1_0_27_2_0() { return cFragmentsREGULAR_FRAGMENTParserRuleCall_1_0_27_2_0; }

		//fragments+="story"
		public Assignment getFragmentsAssignment_1_0_28() { return cFragmentsAssignment_1_0_28; }

		//"story"
		public Keyword getFragmentsStoryKeyword_1_0_28_0() { return cFragmentsStoryKeyword_1_0_28_0; }

		//fragments+="titled"
		public Assignment getFragmentsAssignment_1_0_29() { return cFragmentsAssignment_1_0_29; }

		//"titled"
		public Keyword getFragmentsTitledKeyword_1_0_29_0() { return cFragmentsTitledKeyword_1_0_29_0; }

		//(fragments+="Start" | fragments+="The" | fragments+="Start" fragments+="commonsense" | fragments+="Start"
		//fragments+="reflexive" | fragments+="Start" fragments+="description" | fragments+="Start" fragments+="story")?
		public Alternatives getAlternatives_1_1() { return cAlternatives_1_1; }

		//fragments+="Start"
		public Assignment getFragmentsAssignment_1_1_0() { return cFragmentsAssignment_1_1_0; }

		//"Start"
		public Keyword getFragmentsStartKeyword_1_1_0_0() { return cFragmentsStartKeyword_1_1_0_0; }

		//fragments+="The"
		public Assignment getFragmentsAssignment_1_1_1() { return cFragmentsAssignment_1_1_1; }

		//"The"
		public Keyword getFragmentsTheKeyword_1_1_1_0() { return cFragmentsTheKeyword_1_1_1_0; }

		//fragments+="Start" fragments+="commonsense"
		public Group getGroup_1_1_2() { return cGroup_1_1_2; }

		//fragments+="Start"
		public Assignment getFragmentsAssignment_1_1_2_0() { return cFragmentsAssignment_1_1_2_0; }

		//"Start"
		public Keyword getFragmentsStartKeyword_1_1_2_0_0() { return cFragmentsStartKeyword_1_1_2_0_0; }

		//fragments+="commonsense"
		public Assignment getFragmentsAssignment_1_1_2_1() { return cFragmentsAssignment_1_1_2_1; }

		//"commonsense"
		public Keyword getFragmentsCommonsenseKeyword_1_1_2_1_0() { return cFragmentsCommonsenseKeyword_1_1_2_1_0; }

		//fragments+="Start" fragments+="reflexive"
		public Group getGroup_1_1_3() { return cGroup_1_1_3; }

		//fragments+="Start"
		public Assignment getFragmentsAssignment_1_1_3_0() { return cFragmentsAssignment_1_1_3_0; }

		//"Start"
		public Keyword getFragmentsStartKeyword_1_1_3_0_0() { return cFragmentsStartKeyword_1_1_3_0_0; }

		//fragments+="reflexive"
		public Assignment getFragmentsAssignment_1_1_3_1() { return cFragmentsAssignment_1_1_3_1; }

		//"reflexive"
		public Keyword getFragmentsReflexiveKeyword_1_1_3_1_0() { return cFragmentsReflexiveKeyword_1_1_3_1_0; }

		//fragments+="Start" fragments+="description"
		public Group getGroup_1_1_4() { return cGroup_1_1_4; }

		//fragments+="Start"
		public Assignment getFragmentsAssignment_1_1_4_0() { return cFragmentsAssignment_1_1_4_0; }

		//"Start"
		public Keyword getFragmentsStartKeyword_1_1_4_0_0() { return cFragmentsStartKeyword_1_1_4_0_0; }

		//fragments+="description"
		public Assignment getFragmentsAssignment_1_1_4_1() { return cFragmentsAssignment_1_1_4_1; }

		//"description"
		public Keyword getFragmentsDescriptionKeyword_1_1_4_1_0() { return cFragmentsDescriptionKeyword_1_1_4_1_0; }

		//fragments+="Start" fragments+="story"
		public Group getGroup_1_1_5() { return cGroup_1_1_5; }

		//fragments+="Start"
		public Assignment getFragmentsAssignment_1_1_5_0() { return cFragmentsAssignment_1_1_5_0; }

		//"Start"
		public Keyword getFragmentsStartKeyword_1_1_5_0_0() { return cFragmentsStartKeyword_1_1_5_0_0; }

		//fragments+="story"
		public Assignment getFragmentsAssignment_1_1_5_1() { return cFragmentsAssignment_1_1_5_1; }

		//"story"
		public Keyword getFragmentsStoryKeyword_1_1_5_1_0() { return cFragmentsStoryKeyword_1_1_5_1_0; }

		//"."
		public Keyword getFullStopKeyword_1_2() { return cFullStopKeyword_1_2; }
	}

	public class REGULAR_FRAGMENTElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "REGULAR_FRAGMENT");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cQUOTED_TEXTTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cWORDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final Keyword cCommaKeyword_2 = (Keyword)cAlternatives.eContents().get(2);
		private final Keyword cSemicolonKeyword_3 = (Keyword)cAlternatives.eContents().get(3);
		
		//REGULAR_FRAGMENT:
		//	QUOTED_TEXT | WORD | "," | ";";
		public ParserRule getRule() { return rule; }

		//QUOTED_TEXT | WORD | "," | ";"
		public Alternatives getAlternatives() { return cAlternatives; }

		//QUOTED_TEXT
		public RuleCall getQUOTED_TEXTTerminalRuleCall_0() { return cQUOTED_TEXTTerminalRuleCall_0; }

		//WORD
		public RuleCall getWORDTerminalRuleCall_1() { return cWORDTerminalRuleCall_1; }

		//","
		public Keyword getCommaKeyword_2() { return cCommaKeyword_2; }

		//";"
		public Keyword getSemicolonKeyword_3() { return cSemicolonKeyword_3; }
	}
	
	
	private ModelElements pModel;
	private SectionElements pSection;
	private CommonsenseKnowledgeElements pCommonsenseKnowledge;
	private CommonsenseKnowledgeHeaderElements pCommonsenseKnowledgeHeader;
	private ReflexiveKnowledgeElements pReflexiveKnowledge;
	private ReflexiveKnowledgeHeaderElements pReflexiveKnowledgeHeader;
	private ReflexiveDescriptionElements pReflexiveDescription;
	private TheEndFooterElements pTheEndFooter;
	private ReflexiveDescriptionHeaderElements pReflexiveDescriptionHeader;
	private PerspectiveElements pPerspective;
	private PerspectiveHeaderElements pPerspectiveHeader;
	private StoryElements pStory;
	private StoryHeaderElements pStoryHeader;
	private DescriptionElements pDescription;
	private SentenceElements pSentence;
	private REGULAR_FRAGMENTElements pREGULAR_FRAGMENT;
	private TerminalRule tQUOTED_TEXT;
	private TerminalRule tWORD;
	private TerminalRule tSL_COMMENT;
	private TerminalRule tWS;
	private TerminalRule tANY_OTHER;
	
	private final Grammar grammar;

	@Inject
	public GenesisGrammarAccess(GrammarProvider grammarProvider) {
		this.grammar = internalFindGrammar(grammarProvider);
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.csail.genesis.Genesis".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	
	public Grammar getGrammar() {
		return grammar;
	}
	

	
	//Model:
	//	header+=Sentence* sections+=Section*;
	public ModelElements getModelAccess() {
		return (pModel != null) ? pModel : (pModel = new ModelElements());
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}

	//Section:
	//	CommonsenseKnowledge | ReflexiveKnowledge | Perspective;
	public SectionElements getSectionAccess() {
		return (pSection != null) ? pSection : (pSection = new SectionElements());
	}
	
	public ParserRule getSectionRule() {
		return getSectionAccess().getRule();
	}

	//CommonsenseKnowledge:
	//	{CommonsenseKnowledge} name=CommonsenseKnowledgeHeader body=Description;
	public CommonsenseKnowledgeElements getCommonsenseKnowledgeAccess() {
		return (pCommonsenseKnowledge != null) ? pCommonsenseKnowledge : (pCommonsenseKnowledge = new CommonsenseKnowledgeElements());
	}
	
	public ParserRule getCommonsenseKnowledgeRule() {
		return getCommonsenseKnowledgeAccess().getRule();
	}

	//CommonsenseKnowledgeHeader:
	//	"Start" "commonsense" "knowledge" ".";
	public CommonsenseKnowledgeHeaderElements getCommonsenseKnowledgeHeaderAccess() {
		return (pCommonsenseKnowledgeHeader != null) ? pCommonsenseKnowledgeHeader : (pCommonsenseKnowledgeHeader = new CommonsenseKnowledgeHeaderElements());
	}
	
	public ParserRule getCommonsenseKnowledgeHeaderRule() {
		return getCommonsenseKnowledgeHeaderAccess().getRule();
	}

	//ReflexiveKnowledge:
	//	{ReflexiveKnowledge} name=ReflexiveKnowledgeHeader subsections+=ReflexiveDescription*;
	public ReflexiveKnowledgeElements getReflexiveKnowledgeAccess() {
		return (pReflexiveKnowledge != null) ? pReflexiveKnowledge : (pReflexiveKnowledge = new ReflexiveKnowledgeElements());
	}
	
	public ParserRule getReflexiveKnowledgeRule() {
		return getReflexiveKnowledgeAccess().getRule();
	}

	//ReflexiveKnowledgeHeader:
	//	"Start" "reflexive" "knowledge" ".";
	public ReflexiveKnowledgeHeaderElements getReflexiveKnowledgeHeaderAccess() {
		return (pReflexiveKnowledgeHeader != null) ? pReflexiveKnowledgeHeader : (pReflexiveKnowledgeHeader = new ReflexiveKnowledgeHeaderElements());
	}
	
	public ParserRule getReflexiveKnowledgeHeaderRule() {
		return getReflexiveKnowledgeHeaderAccess().getRule();
	}

	//ReflexiveDescription:
	//	{ReflexiveDescription} name=ReflexiveDescriptionHeader body=Description TheEndFooter;
	public ReflexiveDescriptionElements getReflexiveDescriptionAccess() {
		return (pReflexiveDescription != null) ? pReflexiveDescription : (pReflexiveDescription = new ReflexiveDescriptionElements());
	}
	
	public ParserRule getReflexiveDescriptionRule() {
		return getReflexiveDescriptionAccess().getRule();
	}

	//TheEndFooter:
	//	"The" "end" ".";
	public TheEndFooterElements getTheEndFooterAccess() {
		return (pTheEndFooter != null) ? pTheEndFooter : (pTheEndFooter = new TheEndFooterElements());
	}
	
	public ParserRule getTheEndFooterRule() {
		return getTheEndFooterAccess().getRule();
	}

	//ReflexiveDescriptionHeader:
	//	"Start" "description" "of" QUOTED_TEXT ".";
	public ReflexiveDescriptionHeaderElements getReflexiveDescriptionHeaderAccess() {
		return (pReflexiveDescriptionHeader != null) ? pReflexiveDescriptionHeader : (pReflexiveDescriptionHeader = new ReflexiveDescriptionHeaderElements());
	}
	
	public ParserRule getReflexiveDescriptionHeaderRule() {
		return getReflexiveDescriptionHeaderAccess().getRule();
	}

	//Perspective:
	//	{Perspective} name=PerspectiveHeader subsections+=Story*;
	public PerspectiveElements getPerspectiveAccess() {
		return (pPerspective != null) ? pPerspective : (pPerspective = new PerspectiveElements());
	}
	
	public ParserRule getPerspectiveRule() {
		return getPerspectiveAccess().getRule();
	}

	//PerspectiveHeader:
	//	WORD "perspective" ".";
	public PerspectiveHeaderElements getPerspectiveHeaderAccess() {
		return (pPerspectiveHeader != null) ? pPerspectiveHeader : (pPerspectiveHeader = new PerspectiveHeaderElements());
	}
	
	public ParserRule getPerspectiveHeaderRule() {
		return getPerspectiveHeaderAccess().getRule();
	}

	//Story:
	//	{Story} name=StoryHeader body=Description TheEndFooter;
	public StoryElements getStoryAccess() {
		return (pStory != null) ? pStory : (pStory = new StoryElements());
	}
	
	public ParserRule getStoryRule() {
		return getStoryAccess().getRule();
	}

	//StoryHeader:
	//	"Start" "story" "titled" QUOTED_TEXT ".";
	public StoryHeaderElements getStoryHeaderAccess() {
		return (pStoryHeader != null) ? pStoryHeader : (pStoryHeader = new StoryHeaderElements());
	}
	
	public ParserRule getStoryHeaderRule() {
		return getStoryHeaderAccess().getRule();
	}

	////ArbitrarySentences:
	////    {ArbitrarySentences}
	////    (sentences += Sentence)*
	////;
	//Description:
	//	{Description} sentences+=Sentence*;
	public DescriptionElements getDescriptionAccess() {
		return (pDescription != null) ? pDescription : (pDescription = new DescriptionElements());
	}
	
	public ParserRule getDescriptionRule() {
		return getDescriptionAccess().getRule();
	}

	//Sentence:
	//	{Sentence} ((fragments+=REGULAR_FRAGMENT //
	//	// "Start commonsense knowledge" handling.
	//	//
	//	//
	//	// "Start reflexive knowledge" handling.
	//	//
	//	//
	//	// "Start description of <title>" handling.
	//	//
	//	//
	//	// "The end" handling.
	//	//
	//	//
	//	// "Start story titled" handling.
	//	//
	//	//                //
	//	//                // "????? perspective" handling.
	//	//                //
	//	//                (fragments += "perspective")
	//	| fragments+="Start" fragments+="knowledge" | fragments+="Start" fragments+="commonsense" fragments+=REGULAR_FRAGMENT |
	//	fragments+="Start" fragments+="The" | fragments+="Start" fragments+="end" | fragments+="Start" fragments+="of" |
	//	fragments+="Start" fragments+="Start" | fragments+="Start" fragments+=REGULAR_FRAGMENT | fragments+="knowledge" |
	//	fragments+="commonsense" | fragments+="Start" fragments+="reflexive" fragments+=REGULAR_FRAGMENT |
	//	fragments+="reflexive" | fragments+="Start" fragments+="description" fragments+=REGULAR_FRAGMENT |
	//	fragments+="description" | fragments+="of" | fragments+="The" fragments+="commonsense" | fragments+="The"
	//	fragments+="knowledge" | fragments+="The" fragments+="reflexive" | fragments+="The" fragments+="description" |
	//	fragments+="The" fragments+="of" | fragments+="The" fragments+="story" | fragments+="The" fragments+="titled" |
	//	fragments+="The" fragments+="Start" | fragments+="The" fragments+="The" | fragments+="The" fragments+=REGULAR_FRAGMENT
	//	| fragments+="end" | fragments+="Start" fragments+="titled" | fragments+="Start" fragments+="story"
	//	fragments+=REGULAR_FRAGMENT | fragments+="story" | fragments+="titled")* (fragments+="Start" | fragments+="The" |
	//	fragments+="Start" fragments+="commonsense" | fragments+="Start" fragments+="reflexive" | fragments+="Start"
	//	fragments+="description" | fragments+="Start" fragments+="story")? ".");
	public SentenceElements getSentenceAccess() {
		return (pSentence != null) ? pSentence : (pSentence = new SentenceElements());
	}
	
	public ParserRule getSentenceRule() {
		return getSentenceAccess().getRule();
	}

	//REGULAR_FRAGMENT:
	//	QUOTED_TEXT | WORD | "," | ";";
	public REGULAR_FRAGMENTElements getREGULAR_FRAGMENTAccess() {
		return (pREGULAR_FRAGMENT != null) ? pREGULAR_FRAGMENT : (pREGULAR_FRAGMENT = new REGULAR_FRAGMENTElements());
	}
	
	public ParserRule getREGULAR_FRAGMENTRule() {
		return getREGULAR_FRAGMENTAccess().getRule();
	}

	//terminal QUOTED_TEXT:
	//	"\"" !"\""* "\"";
	public TerminalRule getQUOTED_TEXTRule() {
		return (tQUOTED_TEXT != null) ? tQUOTED_TEXT : (tQUOTED_TEXT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "QUOTED_TEXT"));
	} 

	//terminal WORD:
	//	("0".."9" | "a".."z" | "A".."Z" | "_" | "\"" | "\'")+;
	public TerminalRule getWORDRule() {
		return (tWORD != null) ? tWORD : (tWORD = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "WORD"));
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return (tSL_COMMENT != null) ? tSL_COMMENT : (tSL_COMMENT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "SL_COMMENT"));
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return (tWS != null) ? tWS : (tWS = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "WS"));
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return (tANY_OTHER != null) ? tANY_OTHER : (tANY_OTHER = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "ANY_OTHER"));
	} 
}
