/*
* generated by Xtext
*/
package org.csail.genesis.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.csail.genesis.services.GenesisGrammarAccess;

public class GenesisParser extends AbstractContentAssistParser {
	
	@Inject
	private GenesisGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.csail.genesis.ui.contentassist.antlr.internal.InternalGenesisParser createParser() {
		org.csail.genesis.ui.contentassist.antlr.internal.InternalGenesisParser result = new org.csail.genesis.ui.contentassist.antlr.internal.InternalGenesisParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getSectionAccess().getAlternatives(), "rule__Section__Alternatives");
					put(grammarAccess.getSentenceAccess().getAlternatives_1_0(), "rule__Sentence__Alternatives_1_0");
					put(grammarAccess.getSentenceAccess().getAlternatives_1_1(), "rule__Sentence__Alternatives_1_1");
					put(grammarAccess.getREGULAR_FRAGMENTAccess().getAlternatives(), "rule__REGULAR_FRAGMENT__Alternatives");
					put(grammarAccess.getModelAccess().getGroup(), "rule__Model__Group__0");
					put(grammarAccess.getCommonsenseKnowledgeAccess().getGroup(), "rule__CommonsenseKnowledge__Group__0");
					put(grammarAccess.getCommonsenseKnowledgeHeaderAccess().getGroup(), "rule__CommonsenseKnowledgeHeader__Group__0");
					put(grammarAccess.getReflexiveKnowledgeAccess().getGroup(), "rule__ReflexiveKnowledge__Group__0");
					put(grammarAccess.getReflexiveKnowledgeHeaderAccess().getGroup(), "rule__ReflexiveKnowledgeHeader__Group__0");
					put(grammarAccess.getReflexiveDescriptionAccess().getGroup(), "rule__ReflexiveDescription__Group__0");
					put(grammarAccess.getTheEndFooterAccess().getGroup(), "rule__TheEndFooter__Group__0");
					put(grammarAccess.getReflexiveDescriptionHeaderAccess().getGroup(), "rule__ReflexiveDescriptionHeader__Group__0");
					put(grammarAccess.getPerspectiveAccess().getGroup(), "rule__Perspective__Group__0");
					put(grammarAccess.getPerspectiveHeaderAccess().getGroup(), "rule__PerspectiveHeader__Group__0");
					put(grammarAccess.getStoryAccess().getGroup(), "rule__Story__Group__0");
					put(grammarAccess.getStoryHeaderAccess().getGroup(), "rule__StoryHeader__Group__0");
					put(grammarAccess.getDescriptionAccess().getGroup(), "rule__Description__Group__0");
					put(grammarAccess.getSentenceAccess().getGroup(), "rule__Sentence__Group__0");
					put(grammarAccess.getSentenceAccess().getGroup_1(), "rule__Sentence__Group_1__0");
					put(grammarAccess.getSentenceAccess().getGroup_1_0_1(), "rule__Sentence__Group_1_0_1__0");
					put(grammarAccess.getSentenceAccess().getGroup_1_0_2(), "rule__Sentence__Group_1_0_2__0");
					put(grammarAccess.getSentenceAccess().getGroup_1_0_3(), "rule__Sentence__Group_1_0_3__0");
					put(grammarAccess.getSentenceAccess().getGroup_1_0_4(), "rule__Sentence__Group_1_0_4__0");
					put(grammarAccess.getSentenceAccess().getGroup_1_0_5(), "rule__Sentence__Group_1_0_5__0");
					put(grammarAccess.getSentenceAccess().getGroup_1_0_6(), "rule__Sentence__Group_1_0_6__0");
					put(grammarAccess.getSentenceAccess().getGroup_1_0_7(), "rule__Sentence__Group_1_0_7__0");
					put(grammarAccess.getSentenceAccess().getGroup_1_0_10(), "rule__Sentence__Group_1_0_10__0");
					put(grammarAccess.getSentenceAccess().getGroup_1_0_12(), "rule__Sentence__Group_1_0_12__0");
					put(grammarAccess.getSentenceAccess().getGroup_1_0_15(), "rule__Sentence__Group_1_0_15__0");
					put(grammarAccess.getSentenceAccess().getGroup_1_0_16(), "rule__Sentence__Group_1_0_16__0");
					put(grammarAccess.getSentenceAccess().getGroup_1_0_17(), "rule__Sentence__Group_1_0_17__0");
					put(grammarAccess.getSentenceAccess().getGroup_1_0_18(), "rule__Sentence__Group_1_0_18__0");
					put(grammarAccess.getSentenceAccess().getGroup_1_0_19(), "rule__Sentence__Group_1_0_19__0");
					put(grammarAccess.getSentenceAccess().getGroup_1_0_20(), "rule__Sentence__Group_1_0_20__0");
					put(grammarAccess.getSentenceAccess().getGroup_1_0_21(), "rule__Sentence__Group_1_0_21__0");
					put(grammarAccess.getSentenceAccess().getGroup_1_0_22(), "rule__Sentence__Group_1_0_22__0");
					put(grammarAccess.getSentenceAccess().getGroup_1_0_23(), "rule__Sentence__Group_1_0_23__0");
					put(grammarAccess.getSentenceAccess().getGroup_1_0_24(), "rule__Sentence__Group_1_0_24__0");
					put(grammarAccess.getSentenceAccess().getGroup_1_0_26(), "rule__Sentence__Group_1_0_26__0");
					put(grammarAccess.getSentenceAccess().getGroup_1_0_27(), "rule__Sentence__Group_1_0_27__0");
					put(grammarAccess.getSentenceAccess().getGroup_1_1_2(), "rule__Sentence__Group_1_1_2__0");
					put(grammarAccess.getSentenceAccess().getGroup_1_1_3(), "rule__Sentence__Group_1_1_3__0");
					put(grammarAccess.getSentenceAccess().getGroup_1_1_4(), "rule__Sentence__Group_1_1_4__0");
					put(grammarAccess.getSentenceAccess().getGroup_1_1_5(), "rule__Sentence__Group_1_1_5__0");
					put(grammarAccess.getModelAccess().getHeaderAssignment_0(), "rule__Model__HeaderAssignment_0");
					put(grammarAccess.getModelAccess().getSectionsAssignment_1(), "rule__Model__SectionsAssignment_1");
					put(grammarAccess.getCommonsenseKnowledgeAccess().getNameAssignment_1(), "rule__CommonsenseKnowledge__NameAssignment_1");
					put(grammarAccess.getCommonsenseKnowledgeAccess().getBodyAssignment_2(), "rule__CommonsenseKnowledge__BodyAssignment_2");
					put(grammarAccess.getReflexiveKnowledgeAccess().getNameAssignment_1(), "rule__ReflexiveKnowledge__NameAssignment_1");
					put(grammarAccess.getReflexiveKnowledgeAccess().getSubsectionsAssignment_2(), "rule__ReflexiveKnowledge__SubsectionsAssignment_2");
					put(grammarAccess.getReflexiveDescriptionAccess().getNameAssignment_1(), "rule__ReflexiveDescription__NameAssignment_1");
					put(grammarAccess.getReflexiveDescriptionAccess().getBodyAssignment_2(), "rule__ReflexiveDescription__BodyAssignment_2");
					put(grammarAccess.getPerspectiveAccess().getNameAssignment_1(), "rule__Perspective__NameAssignment_1");
					put(grammarAccess.getPerspectiveAccess().getSubsectionsAssignment_2(), "rule__Perspective__SubsectionsAssignment_2");
					put(grammarAccess.getStoryAccess().getNameAssignment_1(), "rule__Story__NameAssignment_1");
					put(grammarAccess.getStoryAccess().getBodyAssignment_2(), "rule__Story__BodyAssignment_2");
					put(grammarAccess.getDescriptionAccess().getSentencesAssignment_1(), "rule__Description__SentencesAssignment_1");
					put(grammarAccess.getSentenceAccess().getFragmentsAssignment_1_0_0(), "rule__Sentence__FragmentsAssignment_1_0_0");
					put(grammarAccess.getSentenceAccess().getFragmentsAssignment_1_0_1_0(), "rule__Sentence__FragmentsAssignment_1_0_1_0");
					put(grammarAccess.getSentenceAccess().getFragmentsAssignment_1_0_1_1(), "rule__Sentence__FragmentsAssignment_1_0_1_1");
					put(grammarAccess.getSentenceAccess().getFragmentsAssignment_1_0_2_0(), "rule__Sentence__FragmentsAssignment_1_0_2_0");
					put(grammarAccess.getSentenceAccess().getFragmentsAssignment_1_0_2_1(), "rule__Sentence__FragmentsAssignment_1_0_2_1");
					put(grammarAccess.getSentenceAccess().getFragmentsAssignment_1_0_2_2(), "rule__Sentence__FragmentsAssignment_1_0_2_2");
					put(grammarAccess.getSentenceAccess().getFragmentsAssignment_1_0_3_0(), "rule__Sentence__FragmentsAssignment_1_0_3_0");
					put(grammarAccess.getSentenceAccess().getFragmentsAssignment_1_0_3_1(), "rule__Sentence__FragmentsAssignment_1_0_3_1");
					put(grammarAccess.getSentenceAccess().getFragmentsAssignment_1_0_4_0(), "rule__Sentence__FragmentsAssignment_1_0_4_0");
					put(grammarAccess.getSentenceAccess().getFragmentsAssignment_1_0_4_1(), "rule__Sentence__FragmentsAssignment_1_0_4_1");
					put(grammarAccess.getSentenceAccess().getFragmentsAssignment_1_0_5_0(), "rule__Sentence__FragmentsAssignment_1_0_5_0");
					put(grammarAccess.getSentenceAccess().getFragmentsAssignment_1_0_5_1(), "rule__Sentence__FragmentsAssignment_1_0_5_1");
					put(grammarAccess.getSentenceAccess().getFragmentsAssignment_1_0_6_0(), "rule__Sentence__FragmentsAssignment_1_0_6_0");
					put(grammarAccess.getSentenceAccess().getFragmentsAssignment_1_0_6_1(), "rule__Sentence__FragmentsAssignment_1_0_6_1");
					put(grammarAccess.getSentenceAccess().getFragmentsAssignment_1_0_7_0(), "rule__Sentence__FragmentsAssignment_1_0_7_0");
					put(grammarAccess.getSentenceAccess().getFragmentsAssignment_1_0_7_1(), "rule__Sentence__FragmentsAssignment_1_0_7_1");
					put(grammarAccess.getSentenceAccess().getFragmentsAssignment_1_0_8(), "rule__Sentence__FragmentsAssignment_1_0_8");
					put(grammarAccess.getSentenceAccess().getFragmentsAssignment_1_0_9(), "rule__Sentence__FragmentsAssignment_1_0_9");
					put(grammarAccess.getSentenceAccess().getFragmentsAssignment_1_0_10_0(), "rule__Sentence__FragmentsAssignment_1_0_10_0");
					put(grammarAccess.getSentenceAccess().getFragmentsAssignment_1_0_10_1(), "rule__Sentence__FragmentsAssignment_1_0_10_1");
					put(grammarAccess.getSentenceAccess().getFragmentsAssignment_1_0_10_2(), "rule__Sentence__FragmentsAssignment_1_0_10_2");
					put(grammarAccess.getSentenceAccess().getFragmentsAssignment_1_0_11(), "rule__Sentence__FragmentsAssignment_1_0_11");
					put(grammarAccess.getSentenceAccess().getFragmentsAssignment_1_0_12_0(), "rule__Sentence__FragmentsAssignment_1_0_12_0");
					put(grammarAccess.getSentenceAccess().getFragmentsAssignment_1_0_12_1(), "rule__Sentence__FragmentsAssignment_1_0_12_1");
					put(grammarAccess.getSentenceAccess().getFragmentsAssignment_1_0_12_2(), "rule__Sentence__FragmentsAssignment_1_0_12_2");
					put(grammarAccess.getSentenceAccess().getFragmentsAssignment_1_0_13(), "rule__Sentence__FragmentsAssignment_1_0_13");
					put(grammarAccess.getSentenceAccess().getFragmentsAssignment_1_0_14(), "rule__Sentence__FragmentsAssignment_1_0_14");
					put(grammarAccess.getSentenceAccess().getFragmentsAssignment_1_0_15_0(), "rule__Sentence__FragmentsAssignment_1_0_15_0");
					put(grammarAccess.getSentenceAccess().getFragmentsAssignment_1_0_15_1(), "rule__Sentence__FragmentsAssignment_1_0_15_1");
					put(grammarAccess.getSentenceAccess().getFragmentsAssignment_1_0_16_0(), "rule__Sentence__FragmentsAssignment_1_0_16_0");
					put(grammarAccess.getSentenceAccess().getFragmentsAssignment_1_0_16_1(), "rule__Sentence__FragmentsAssignment_1_0_16_1");
					put(grammarAccess.getSentenceAccess().getFragmentsAssignment_1_0_17_0(), "rule__Sentence__FragmentsAssignment_1_0_17_0");
					put(grammarAccess.getSentenceAccess().getFragmentsAssignment_1_0_17_1(), "rule__Sentence__FragmentsAssignment_1_0_17_1");
					put(grammarAccess.getSentenceAccess().getFragmentsAssignment_1_0_18_0(), "rule__Sentence__FragmentsAssignment_1_0_18_0");
					put(grammarAccess.getSentenceAccess().getFragmentsAssignment_1_0_18_1(), "rule__Sentence__FragmentsAssignment_1_0_18_1");
					put(grammarAccess.getSentenceAccess().getFragmentsAssignment_1_0_19_0(), "rule__Sentence__FragmentsAssignment_1_0_19_0");
					put(grammarAccess.getSentenceAccess().getFragmentsAssignment_1_0_19_1(), "rule__Sentence__FragmentsAssignment_1_0_19_1");
					put(grammarAccess.getSentenceAccess().getFragmentsAssignment_1_0_20_0(), "rule__Sentence__FragmentsAssignment_1_0_20_0");
					put(grammarAccess.getSentenceAccess().getFragmentsAssignment_1_0_20_1(), "rule__Sentence__FragmentsAssignment_1_0_20_1");
					put(grammarAccess.getSentenceAccess().getFragmentsAssignment_1_0_21_0(), "rule__Sentence__FragmentsAssignment_1_0_21_0");
					put(grammarAccess.getSentenceAccess().getFragmentsAssignment_1_0_21_1(), "rule__Sentence__FragmentsAssignment_1_0_21_1");
					put(grammarAccess.getSentenceAccess().getFragmentsAssignment_1_0_22_0(), "rule__Sentence__FragmentsAssignment_1_0_22_0");
					put(grammarAccess.getSentenceAccess().getFragmentsAssignment_1_0_22_1(), "rule__Sentence__FragmentsAssignment_1_0_22_1");
					put(grammarAccess.getSentenceAccess().getFragmentsAssignment_1_0_23_0(), "rule__Sentence__FragmentsAssignment_1_0_23_0");
					put(grammarAccess.getSentenceAccess().getFragmentsAssignment_1_0_23_1(), "rule__Sentence__FragmentsAssignment_1_0_23_1");
					put(grammarAccess.getSentenceAccess().getFragmentsAssignment_1_0_24_0(), "rule__Sentence__FragmentsAssignment_1_0_24_0");
					put(grammarAccess.getSentenceAccess().getFragmentsAssignment_1_0_24_1(), "rule__Sentence__FragmentsAssignment_1_0_24_1");
					put(grammarAccess.getSentenceAccess().getFragmentsAssignment_1_0_25(), "rule__Sentence__FragmentsAssignment_1_0_25");
					put(grammarAccess.getSentenceAccess().getFragmentsAssignment_1_0_26_0(), "rule__Sentence__FragmentsAssignment_1_0_26_0");
					put(grammarAccess.getSentenceAccess().getFragmentsAssignment_1_0_26_1(), "rule__Sentence__FragmentsAssignment_1_0_26_1");
					put(grammarAccess.getSentenceAccess().getFragmentsAssignment_1_0_27_0(), "rule__Sentence__FragmentsAssignment_1_0_27_0");
					put(grammarAccess.getSentenceAccess().getFragmentsAssignment_1_0_27_1(), "rule__Sentence__FragmentsAssignment_1_0_27_1");
					put(grammarAccess.getSentenceAccess().getFragmentsAssignment_1_0_27_2(), "rule__Sentence__FragmentsAssignment_1_0_27_2");
					put(grammarAccess.getSentenceAccess().getFragmentsAssignment_1_0_28(), "rule__Sentence__FragmentsAssignment_1_0_28");
					put(grammarAccess.getSentenceAccess().getFragmentsAssignment_1_0_29(), "rule__Sentence__FragmentsAssignment_1_0_29");
					put(grammarAccess.getSentenceAccess().getFragmentsAssignment_1_1_0(), "rule__Sentence__FragmentsAssignment_1_1_0");
					put(grammarAccess.getSentenceAccess().getFragmentsAssignment_1_1_1(), "rule__Sentence__FragmentsAssignment_1_1_1");
					put(grammarAccess.getSentenceAccess().getFragmentsAssignment_1_1_2_0(), "rule__Sentence__FragmentsAssignment_1_1_2_0");
					put(grammarAccess.getSentenceAccess().getFragmentsAssignment_1_1_2_1(), "rule__Sentence__FragmentsAssignment_1_1_2_1");
					put(grammarAccess.getSentenceAccess().getFragmentsAssignment_1_1_3_0(), "rule__Sentence__FragmentsAssignment_1_1_3_0");
					put(grammarAccess.getSentenceAccess().getFragmentsAssignment_1_1_3_1(), "rule__Sentence__FragmentsAssignment_1_1_3_1");
					put(grammarAccess.getSentenceAccess().getFragmentsAssignment_1_1_4_0(), "rule__Sentence__FragmentsAssignment_1_1_4_0");
					put(grammarAccess.getSentenceAccess().getFragmentsAssignment_1_1_4_1(), "rule__Sentence__FragmentsAssignment_1_1_4_1");
					put(grammarAccess.getSentenceAccess().getFragmentsAssignment_1_1_5_0(), "rule__Sentence__FragmentsAssignment_1_1_5_0");
					put(grammarAccess.getSentenceAccess().getFragmentsAssignment_1_1_5_1(), "rule__Sentence__FragmentsAssignment_1_1_5_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.csail.genesis.ui.contentassist.antlr.internal.InternalGenesisParser typedParser = (org.csail.genesis.ui.contentassist.antlr.internal.InternalGenesisParser) parser;
			typedParser.entryRuleModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_SL_COMMENT" };
	}
	
	public GenesisGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(GenesisGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
