/**
 * generated by Xtext
 */
package org.csail.genesis.validation;

import org.csail.genesis.validation.AbstractGenesisValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class GenesisValidator extends AbstractGenesisValidator {
}
