/*
 * generated by Xtext
 */
package org.csail.genesis.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractGenesisValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(org.csail.genesis.genesis.GenesisPackage.eINSTANCE);
		return result;
	}
}
