/*
 * generated by Xtext
 */
package org.csail.genesis.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.csail.genesis.ui.internal.GenesisActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class GenesisExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return GenesisActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return GenesisActivator.getInstance().getInjector(GenesisActivator.ORG_CSAIL_GENESIS_GENESIS);
	}
	
}
