/*
 * generated by Xtext
 */
package org.csail.genesis;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class GenesisRuntimeModule extends org.csail.genesis.AbstractGenesisRuntimeModule {

}
