/**
 * generated by Xtext
 */
package org.csail.genesis.ui.outline;

import org.csail.genesis.genesis.CommonsenseKnowledge;
import org.csail.genesis.genesis.ReflexiveDescription;
import org.csail.genesis.genesis.Story;
import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * Customization of the default outline structure.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#outline
 */
@SuppressWarnings("all")
public class GenesisOutlineTreeProvider extends DefaultOutlineTreeProvider {
  public boolean _isLeaf(final CommonsenseKnowledge node) {
    return true;
  }
  
  public boolean _isLeaf(final ReflexiveDescription node) {
    return true;
  }
  
  public boolean _isLeaf(final Story node) {
    return true;
  }
}
